include $(TOPDIR)/rules.mk

LUCI_TITLE:=Cowboy Bebop Manager Private Theme
LUCI_DEPENDS:=+luci-base
LUCI_PKGARCH:=all
LUCI_MINIFY_UT:=0

PKG_NAME:=luci-theme-cowboy-bebop
PKG_VERSION:=1.0.0
PKG_RELEASE:=1
PKG_LICENSE:=MIT
PKG_MAINTAINER:=Abdulrahman Ayad

include $(TOPDIR)/feeds/luci/luci.mk
